version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - 8080:3000
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
  
  db:
    image: mysql:8.0.30-debian
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 1G
      

# Docker Compose CLI 2
#CMD e Entrypoint